server:
  port: 3000

spring:
  kafka: # Não tem autenticação ou coisa do tipo
    # Configuração principal. Define o endereço do broker do Kafka.
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      notify-ending: notify-ending
    consumer:
      # Define o ID do grupo de consumidores para este serviço.
      # Cada serviço deve ter um ID de grupo único.
      group-id: order-group
      # Define o comportamento do consumidor quando não há offsets iniciais.
      auto-offset-reset: latest

  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017}

logging:
  level:
    org:
      apache:
        kafka: OFF
